apiVersion: v1
kind: Service
metadata:
  name: brat
  labels:
    app: brat
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 31817
  selector:
    app: brat
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: brat
  labels:
    app: brat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brat
  template:
    metadata:
      labels:
        app: brat
    spec:
      containers:
      - name: brat
	image: harbor.richinfoai.com/richinfoai/brat:202101141551-90fa5e4
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 3Gi
        volumeMounts:
          - name: brat-volume
            mountPath: /app/data
      volumes:
        - name: brat-volume
          persistentVolumeClaim:
            claimName: modelsdata-pvc
